In [4]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import r2_score,auc,accuracy_score

In [8]:
train=pd.read_csv('data/diabete/diabetes_train.csv')
test=pd.read_csv('data/diabete/diabetes_test.csv')

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   id                        576 non-null    int64  
 1   Pregnancies               576 non-null    int64  
 2   Glucose                   576 non-null    int64  
 3   BloodPressure             576 non-null    int64  
 4   SkinThickness             576 non-null    int64  
 5   Insulin                   576 non-null    int64  
 6   BMI                       576 non-null    float64
 7   DiabetesPedigreeFunction  576 non-null    float64
 8   Age                       576 non-null    int64  
 9   Outcome                   576 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 45.1 KB


In [12]:
train.head(2)

id  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0  377            1       87             60             37       75  37.2   
1  370            3      173             82             48      465  38.4   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.509   22        0  
1                     2.137   25        1

In [14]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   id                        192 non-null    int64  
 1   Pregnancies               192 non-null    int64  
 2   Glucose                   192 non-null    int64  
 3   BloodPressure             192 non-null    int64  
 4   SkinThickness             192 non-null    int64  
 5   Insulin                   192 non-null    int64  
 6   BMI                       192 non-null    float64
 7   DiabetesPedigreeFunction  192 non-null    float64
 8   Age                       192 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 13.6 KB


# 당뇨병 여부 판단

    예측컬럼: Outcome (0 정상, 1 당뇨) 당뇨병일 확률 예측
    평가지표: roc-auc
    제출파일명: result.csv (1개컬럼, 컬럼명 pred)



In [17]:
# target 분리
target = train.pop('Outcome')

In [19]:
train.shape,test.shape

((576, 9), (192, 9))

In [21]:
target.value_counts()

Outcome
0    381
1    195
Name: count, dtype: int64

In [23]:
# 결측치 확인
train.isnull().sum()

id                          0
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [25]:
# id 제거 
train= train.drop('id',axis=1)
test= test.drop('id',axis=1)

In [27]:
train.shape,test.shape

((576, 8), (192, 8))

In [29]:
rf= RandomForestClassifier(random_state=42)

In [31]:
X_train,X_test,y_train,y_test= train_test_split(train,target)

In [33]:
rf.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [35]:
pred= rf.predict(X_test)

In [39]:
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [41]:
y_test

244    0
76     0
289    0
441    1
341    1
      ..
122    1
358    0
551    1
291    1
298    0
Name: Outcome, Length: 144, dtype: int64

In [43]:
accuracy_score(y_test,pred)

0.7569444444444444

In [49]:
from sklearn.metrics import roc_auc_score

proba= rf.predict_proba(X_test)[:,1]
proba

array([0.25, 0.05, 0.08, 0.37, 0.42, 0.03, 0.37, 0.  , 0.52, 0.39, 0.54,
       0.32, 0.09, 0.11, 0.43, 0.08, 0.51, 0.02, 0.25, 0.8 , 0.21, 0.23,
       0.04, 0.08, 0.  , 0.42, 0.01, 0.05, 0.29, 0.32, 0.52, 0.2 , 0.12,
       0.9 , 0.5 , 0.5 , 0.12, 0.14, 0.15, 0.65, 0.39, 0.5 , 0.19, 0.3 ,
       0.15, 0.21, 0.09, 0.61, 0.41, 0.  , 0.09, 0.29, 0.52, 0.24, 0.03,
       0.54, 0.34, 0.08, 0.93, 0.13, 0.51, 0.7 , 0.12, 0.4 , 0.17, 0.93,
       0.  , 0.61, 0.61, 0.15, 0.58, 0.1 , 0.19, 0.02, 0.  , 0.93, 0.06,
       0.68, 0.06, 0.67, 0.37, 0.13, 0.85, 0.15, 0.2 , 0.11, 0.76, 0.14,
       0.12, 0.01, 0.36, 0.27, 0.72, 0.15, 0.17, 0.49, 0.04, 0.7 , 0.6 ,
       0.58, 0.47, 0.31, 0.31, 0.62, 0.26, 0.31, 0.16, 0.05, 0.17, 0.02,
       0.32, 0.1 , 0.02, 0.36, 0.51, 0.14, 0.63, 0.05, 0.67, 0.57, 0.01,
       0.18, 0.47, 0.  , 0.25, 0.11, 0.18, 0.63, 0.02, 0.56, 0.65, 0.41,
       0.13, 0.66, 0.93, 0.39, 0.62, 0.63, 0.09, 0.07, 0.  , 0.22, 0.7 ,
       0.1 ])

In [51]:
roc_auc =roc_auc_score(y_test,proba)

In [53]:
print(roc_auc)

0.8172268907563025


In [57]:
# help(roc_auc_score) y_score로 넣을 값은 predict_proba(X)[:, 1] 이나 decision_function(X) 중 하나라는 뜻

In [65]:
pred = rf.predict_proba(test)[:,1]

In [67]:
pred

array([0.55, 0.54, 0.01, 0.76, 0.32, 0.36, 0.64, 0.02, 0.37, 0.41, 0.62,
       0.1 , 0.16, 0.64, 0.06, 0.53, 0.14, 0.78, 0.61, 0.68, 0.33, 0.83,
       0.01, 0.82, 0.43, 0.2 , 0.7 , 0.07, 0.34, 0.78, 0.65, 0.21, 0.58,
       0.02, 0.17, 0.28, 0.05, 0.  , 0.15, 0.26, 0.27, 0.15, 0.41, 0.43,
       0.16, 0.26, 0.41, 0.11, 0.3 , 0.3 , 0.78, 0.58, 0.51, 0.6 , 0.67,
       0.06, 0.01, 0.71, 0.72, 0.31, 0.31, 0.32, 0.51, 0.48, 0.36, 0.16,
       0.37, 0.22, 0.51, 0.28, 0.39, 0.01, 0.39, 0.76, 0.02, 0.79, 0.59,
       0.65, 0.72, 0.11, 0.16, 0.29, 0.21, 0.43, 0.19, 0.6 , 0.14, 0.27,
       0.01, 0.66, 0.01, 0.28, 0.85, 0.32, 0.7 , 0.7 , 0.27, 0.28, 0.45,
       0.15, 0.82, 0.47, 0.22, 0.46, 0.4 , 0.14, 0.52, 0.13, 0.26, 0.77,
       0.12, 0.14, 0.68, 0.08, 0.16, 0.  , 0.57, 0.03, 0.03, 0.64, 0.48,
       0.33, 0.77, 0.4 , 0.62, 0.01, 0.68, 0.47, 0.01, 0.19, 0.53, 0.1 ,
       0.1 , 0.52, 0.76, 0.03, 0.2 , 0.34, 0.57, 0.59, 0.65, 0.09, 0.02,
       0.23, 0.02, 0.57, 0.64, 0.81, 0.01, 0.11, 0.

In [69]:
pred= pd.DataFrame({'pred':pred})
pred

pred
0    0.55
1    0.54
2    0.01
3    0.76
4    0.32
..    ...
187  0.97
188  0.26
189  0.82
190  0.53
191  0.23

[192 rows x 1 columns]

In [78]:
pred.to_csv("data/diabete/diabetes_result.csv",index=False)